{{- if not (.Capabilities.APIVersions.Has "slack.stakater.com/v1alpha1") -}}
    {{- fail "Required CRDs are missing, slack-operator-crds chart is a pre-requisite of this chart" }}
{{ end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slack-operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slack-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9443
      protocol: TCP
      name: http
  selector:
    {{- include "slack-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slack-operator.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slack-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    {{- include "slack-operator.selectorLabels" . | nindent 4 }}